# Generated by Django 5.1.3 on 2025-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="blog_commen_created_79f39f_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="blog_commen_created_0e6ed4_idx"
            ),
        ),
    ]
